### ISSUE TITLE
Multiple Public Key Import

### ISSUE THREAD

**Issue by mark-hedera** [hashgraph/hedera-transaction-tool-demo#103]
### Problem

End-user currently has to share and import public keys manually

### Solution

Allow the import of multiple public keys via Zip file from Home Screen, similar to an Account Import. The total number of keys to be imported would be displayed in the item detail and key names would be based on file names of the individual key files within the Zip file.

**Comment by DSMatusevich** [comment]
Design Changes:

- The files will be bundled on the App side, not in the Folder side. In other words, the files will be uploaded individually, but they will be shown as one card on the Home screen
- We will show one card for new information and another for updates
- Each card will have a list of the files, with a checkbox attached to each. The user can decline individual files by unchecking the box
- Since they behave in a similar manner, the account info files will also be bundled.
