### ISSUE TITLE
Fee Payer drop-down in settings highlights two options at one time

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#125]
### Description

Reference this issue:https://github.com/hashgraph/hedera-transaction-tool-demo/issues/117

### Steps to reproduce

see above

### Hedera network

testnet

### Version

0.4.0-alpha.2

**Comment by DSMatusevich** [comment]
JavaFX has two similar controls: ComboBox and ChoiceBox. They are both dropdowns. The fee payer is a ComboBox, because it needs to be editable (in case the user adds an account that is not in the dropdown) 

If I want to change the highlight behavior I need to use a ChoiceBox, but that is not editable, which would then require much less elegant solutions for adding a fee payer.
