### ISSUE TITLE
Cannot enter a new fee payer after the first one is entered

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#133]
### Description

- Added a new account 9401
- Entered a fee payer account
- Click request info
- Add another account with a different fee payer
- Cannot enter a new fee payer

### Steps to reproduce

see above

### Hedera network

other

### Version

0.4.0-alpha.3

### Operating system

Other

**Comment by DSMatusevich** [comment]
The app remembers only the last custom fee payer: if you enter a second custom fee payer it will forget the previous one.

The idea is that the first thing the user would do is to request the info on the custom fee payer, which would add it to the list of defaults.

I can make it so that several custom fee payers are stored. Is this the direction we want to go?

**Comment by SimiHunjan** [comment]
This is for adding a new account. I click the drop down for adding a new account -> enter an account ID -> enter a fee payer account -> click request info -> select a key. If I go back and change to mainnet -> enter a new account ID like 805 -> Select the fee payer to be 805 I cannot do that. It does not allow me to enter a new fee payer account.

**Comment by DSMatusevich** [comment]
No, you cannot enter a custom fee payer in the Accounts dropdown. Only in settings. 

The dropdown in the accounts page only allows you to switch between fee payers (including the one custom payer that might have been added via the settings)

**Comment by SimiHunjan** [comment]
fixed
