### ISSUE TITLE
"Transaction Tool is downloading..." message appeared repeatedly until the tool opened

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#372]
### Description

There were about 100 items that were uploaded to OneDrive for the user to accept or to a sign transactions. When the tool was opened a message popped up repeatedly until the tool opened. It seemed as if the tool was opening when some of the files were still downloading from OneDrive.

![Image from iOS (3)](https://user-images.githubusercontent.com/21989138/179792607-ec673031-bb53-4d2c-aeb7-9a7c12677edf.jpg)

### Steps to reproduce

1. Add ~100 files to the input files folder in OneDrive
2. Open the Transaction Tool application

### Hedera network

other

### Version

v0.10

**Comment by lbaird** [comment]
Or maybe the tool is opening a separate popup for each file it loads, even
if that file takes a small fraction of a second to load?

A better approach is to open a single popup saying “loading files”, and
have it disappear only after all the files are loaded. It could have both a
cancel button and a progress bar. And not pop up until we’ve spent at least
one second loading.

**Comment by SimiHunjan** [comment]
https://user-images.githubusercontent.com/21989138/182242624-9395653b-9cd5-4ff6-8457-274cf698a0ed.MOV

**Comment by statop** [comment]
This is a dialog from the macos subsystem that handles "remote" file systems. In this case, it seems that onedrive is "lazy" loading the files. Transaction tool has to inspect all the files when they are visible. This causes macos to tell onedrive to download the file, and triggers this dialog. Since the files are small, they quickly download.
